site:
  key: :cca
  subdomain: "mhc"
  domain_name: "hbxshop.org"
  site_title: "Access Health Connecticut"
  home_url: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
  home_business_url: "https://www.mahealthconnector.org/business/"
  help_url: "https://www.mahealthconnector.org/business/help-center"
  faqs_url: "https://www.mahealthconnector.org/business/help-center/faqs"
  business_resource_center_url: "https://www.mahealthconnector.org/business/business-resource-center"
  nondiscrimination_notice_url: "https://www.MAhealthconnector.org/site-policies/nondiscrimination-notice"
  main_web_address_url: "https://www.MAhealthconnector.org"
  policies_url: "https://www.mahealthconnector.org/about/policy-center/policies"
  invoice_bill_url: "https://ww2.e-billexpress.com/ebpp/maconnector/"
  payment_pdf_url: "https://www.mahealthconnector.org/help-center-answers/how-to-pay-your-premiums-online"
  user_sign_in_url: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
  website_name: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
  main_web_address: "https://www.accesshealthct.com/AHCT/LandingPageCTHIX"
  health_care_website: "www.healthcare.gov"
  health_care_website_url: "https://www.healthcare.gov"
  short_name: "Access Health Connecticut"
  byline: "Connecticut's Official Health Insurance Marketplace"
  long_name: "Access Health Connecticut"
  copyright_period_start: "2017"
  header_message: "Connecticut's Official Health Insurance Marketplace"
  logo_file_name: "logo_ct.png"
  make_their_premium_payments_online: "https://ww2.e-billexpress.com/ebpp/MAConnector/"
  tab_icon: 'favicon.ico'
  mailer_logo_file_name: "health_connector.png"
  employer_application_deadline_link: "https://www.mahealthconnector.org/business/employers/employer-resources-and-information/employer-coverage-deadlines"
  s3_prefix: "mhc"
  broker_quoting_enabled: false
  broker_claim_quoting_enabled: true
  guidance_for_business_owners_url: "https://www.mahealthconnector.org/help-center-answers/guidance-for-business-owners"
  use_default_devise_path: true
  plan_options_title_for_ma: true
  create_routes: ['/insured/employee/privacy','/employers/employer_profiles/new']
  sign_in_routes: ['/families/home']
  shop_find_your_doctor_url: "https://ma.checkbookhealth.org/mashop"
  document_verification_checklist_url: "https://www.mahealthconnector.org/business/business-resource-center/employer-verification-checklist"
  terms_and_conditions_url: "https://www.mahealthconnector.org/business/brokers/certification/terms-and-conditions"
  certification_url: "https://www.mahealthconnector.org/business/brokers/certification"
  registration_path: "https://www.mahealthconnector.org/business/create-a-business-account"
  home_forms_url: "https://dchealthlink.com/forms"
  forms_name: "DCHealthLink.com/forms"
  healthcare_name: "www.healthcare.gov"
  healthcare_url: "https://www.healthcare.gov/"
  irs_url: "https://www.irs.gov/"
  exchange_hbx_id: "MA0"
  tufts_premier_url: "https://tuftshealthplan.com/contact-us/members"
  mail_address: "noreply@healthconnector.org"
  privacy_policy: "https://www.mahealthconnector.org/site-policies/privacy-policy"
  late_rates_message: "Due to a delay, premiums for some coverage effective dates are not available yet. Please check again soon to see if this information has been updated. You can also contact Customer Service or your broker if you need help."

  exchange_name: "Access Health Connecticut"
  social_media:
    facebook_url: ""

contact_center:
  name: "Health Connector's Customer Care Center"
  alt_name: "Health Connector Customer Service"
  phone_number: "1-888-813-9220"
  fax: "1-617-933-3099"
  alt_fax: "617-722-4033"
  tty_number: "711"
  alt_phone_number: "1-888-813-9220"
  payment_phone_number: "1-888-813-9220"
  ivl_number: "1-877-623-6765"
  ivl_phone_number: "1-877-623-6765"
  email_address: "smallbusiness@accesshealthconnecticut.org"
  small_business_email: "smallbusiness@accesshealthconnecticut.org"
  non_discrimination_email: "Nondiscrimination@state.ma.us"


notices:

  individual_market:
    mail_address:
      address_1: "PO Box 44018"
      city: "Washington"
      zip_code: "20026"

  shop_market:
    mail_address:
      address_1: "1225 I Street, NW"
      address_2: "Suite 400"
      zip_code: "20005"

  mailing_address:
    address_1:
    address_2:
    city:
    state: "DC"
    zip:

  shop:
    attachments:
      non_discrimination_attachment: "shop_non_discrimination_attachment.pdf"
      envelope_without_address: "taglines.pdf"
      employee_appeal_rights: "employee_appeal_rights.pdf"
    partials:
      template: "notifier/notice_kinds/template.html.erb"
      header: "notices/shared/shop_header.html.erb"
      footer: "notices/shared/shop_footer.html.erb"
      layout: "notifier/pdf_layout.html.erb"
  individual:
    attachments:
      blank_page_attachment: "blank.pdf"
      envelope_without_address: "taglines.pdf"
      non_discrimination_attachment: "ivl_non_discrimination.pdf"
      voter_application: "voter_application.pdf"
    partials:
      template: "notifier/notice_kinds/ivl_template.html.erb"
      header: "notices/shared/header_ivl.html.erb"
      footer: "notices/shared/footer_ivl.html.erb"
      layout: "notifier/ivl_pdf_layout.html.erb"

aca:
  state_name: "District of Columbia"
  state_abbreviation: "DC"
  hbx_abbreviation: "DC Health Benefit Exchange"
  market_kinds: ["individual", "shop"]
#
  qle:
    with_in_sixty_days: 60
#

  individual_market:
    monthly_enrollment_due_on: 15
    verification_outstanding_window:
      days: 0
    verification_due:
      days: 95

    open_enrollment:
      start_on: <%= Date.new(2018,11,1) %>
      end_on: <%= Date.new(2019,02,8) %>
    upcoming_open_enrollment:
      start_on: <%= Date.new(2019,11,1) %>
      end_on: <%= Date.new(2020,01,31) %>

    dc_resident_application: true
    transition_family_members_link: true

  shop_market:
    small_market_employee_count_maximum: 50
    employer_contribution_percent_minimum: 50
    employee_participation_ratio_minimum: <%= 2 / 3.0 %>
    non_owner_participation_count_minimum: 1
    binder_payment_due_on: 12
    small_market_active_employee_limit: 200

    earliest_enroll_prior_to_effective_on:
      days: -30
    latest_enroll_after_effective_on:
      days: 30
    latest_enroll_after_employee_roster_correction_on:
      days: 30

    retroactive_coverage_termination_maximum:
      days: -60

    initial_application:
      advertised_deadline_of_month: 1
      publish_due_day_of_month: 5
      earliest_start_prior_to_effective_on:
        months: -3
      appeal_period_after_application_denial:
        days: 30
      # After submitting an ineligible plan year application, time period an Employer must wait
      ineligible_period_after_application_denial:
        days: 90
      quiet_period_end_on: 28

    renewal_application:
      application_submission_soft_deadline: 5
      earliest_start_prior_to_effective_on:
        months: -3
      monthly_open_enrollment_end_on: 13
      publish_due_day_of_month: 10
      force_publish_day_of_month: 11
      open_enrollment:
        minimum_length:
          days: 3
      quiet_period_end_on: 15

    benefit_period:
      length_minimum:
        year: 1
      length_maximum:
        year: 1

    open_enrollment:
      monthly_start_on: 1
      monthly_end_on: 10

      minimum_length:
        days: 5
      maximum_length:
        months: 2

    cobra_enrollment_period:
      months: 6

    group_file:
      new_enrollment_transmit_on: 16
      update_transmit_day_of_week: "friday"

    transmit_employers_immediately: false
    transmit_scheduled_employers: true
    employer_transmission_day_of_month: 16

paper_notice: 'paper-notices'
# Note: Remote Aceess keys ad URL's Provided by DC checkbook

checkbook_services:
    current_year: 2019
    previous_year: 2018
    plan_match: "DC"

aptc_errors:
  effective_date_overflow: "Updates not allowed at this time. Effective Date happens to be after the Policy's life (next year) when following the 15th day rule."
  enrollment_max_smaller_than_applied: "Max Applied APTC for any Enrollment cannot be smaller than the Applied APTC."
  plan_premium_smaller_than_applied: "Applied APTC for any Enrollment cannot be greater than the Plan Premium."
  max_aptc_non_numeric: "Max APTC needs to be a numeric value."
  max_aptc_too_small: "Max APTC should be greater than or equal to the sum of APTC Applied for all enrollments."
  max_aptc_too_big: "Max APTC should be less than 9999.99"

#   ShopOpenEnrollmentBeginDueDayOfMonth = ShopOpenEnrollmentEndDueDayOfMonth - ShopOpenEnrollmentPeriodMinimum
#   ShopPlanYearPublishedDueDayOfMonth = ShopOpenEnrollmentBeginDueDayOfMonth
