
site:
  short_name: "Access Health CT"
  long_name: ""

  call_center: 
    name: "Access Health CT's Customer Care Center"
    phone_number: "1-855-532-5465"

aca:
  state_name: "Connecticut"
  state_abbreviation: "CT"
  ivl: 
    enrollment_due_day_of_month: 15
  shop:
    retroactive_termination_maximum: 60.days
    renewal_period_before_start_on_maximum: 3.months
